config/routes.rb
Rails.application.routes.draw do
  root 'games#new'
  resources :games, except: %i[index edit destroy] do
    scope module: :games do
      resources :restarts, only: :create
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
# == Schema Information
#
# Table name: games
#
#  id             :integer          not null, primary key
#  player1_id     :integer          not null
#  player2_id     :integer          not null
#  winner_id      :integer
#  current_player :integer          default("x")
#  field1         :integer          default("empty")
#  field2         :integer          default("empty")
#  field3         :integer          default("empty")
#  field4         :integer          default("empty")
#  field5         :integer          default("empty")
#  field6         :integer          default("empty")
#  field7         :integer          default("empty")
#  field8         :integer          default("empty")
#  field9         :integer          default("empty")
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
class Game < ApplicationRecord
  belongs_to :player1, class_name: 'Player'
  belongs_to :player2, class_name: 'Player'
  belongs_to :winner, class_name: 'Player', optional: true

  enum current_player: { x: 0, o: 1 }, _prefix: true
  enum field1: { empty: 0, x: 1, o: 2 }, _prefix: true
  enum field2: { empty: 0, x: 1, o: 2 }, _prefix: true
  enum field3: { empty: 0, x: 1, o: 2 }, _prefix: true
  enum field4: { empty: 0, x: 1, o: 2 }, _prefix: true
  enum field5: { empty: 0, x: 1, o: 2 }, _prefix: true
  enum field6: { empty: 0, x: 1, o: 2 }, _prefix: true
  enum field7: { empty: 0, x: 1, o: 2 }, _prefix: true
  enum field8: { empty: 0, x: 1, o: 2 }, _prefix: true
  enum field9: { empty: 0, x: 1, o: 2 }, _prefix: true

  WINNING_COMBINATIONS = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [1, 4, 7],
    [2, 5, 8],
    [3, 6, 9],
    [1, 5, 9],
    [3, 5, 7]
  ].freeze

  def make_step(field_index)
    return false if winner || draw? || invalid_step?(field_index)

    ActiveRecord::Base.transaction do
      update("field#{field_index}": current_player)
      find_winner
      switch_player unless winner
    end
  end

  def player_name
    find_player.name
  end

  def restart
    update(
      winner: nil,
      current_player: 'x',
      field1: 'empty',
      field2: 'empty',
      field3: 'empty',
      field4: 'empty',
      field5: 'empty',
      field6: 'empty',
      field7: 'empty',
      field8: 'empty',
      field9: 'empty'
    )
  end

  def draw?
    (1..9).each do |i|
      return false if send("field#{i}_empty?")
    end
    true
  end

  def win_condition
    WINNING_COMBINATIONS.each do |condition|
      return condition if condition.all? { |field_index| send("field#{field_index}_#{current_player}?") }
    end
    []
  end

  private

  def invalid_step?(field_index)
    (1..9).exclude?(field_index.to_i) || !send("field#{field_index}_empty?")
  end

  def find_player
    current_player_x? ? player1 : player2
  end

  def find_winner
    update(winner: find_player) if win_condition.any?
  end

  def switch_player
    update(current_player: next_player)
  end

  def next_player
    current_player_x? ? 'o' : 'x'
  end
end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Player < ApplicationRecord
  has_many :games, inverse_of: :winner, foreign_key: 'winner_id', dependent: :destroy

  validates :name, length: { minimum: 3, maximum: 30 }, allow_blank: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games/restarts_controller.rb
module Games
  class RestartsController < GamesController
    def create
      game = Game.find(params[:game_id])
      game.restart
      redirect_to game_path(game)
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[show update]
  def new; end

  def create
    game = GameBuilderService.call(params)
    if game
      redirect_to game_path(game)
    else
      redirect_to new_game_path, alert: 'Please, enter the player name (3 symbols min, 30 max)'
    end
  end

  def show; end

  def update
    @game.make_step(params[:field_index])
    redirect_to game_path(@game)
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
  def icon_name(name)
    name == 'x' ? 'close' : 'radio_button_unchecked'
  end

  def winning_class(win_condition, index)
    win_condition.include?(index) ? 'icon-green' : ''
  end
end

app/views/games/new.html.erb
<div class="mdl-card mdl-shadow--2dp">
  <div class="mdl-card__title">
    <h2 class="mdl-card__title-text">Tic-tac-toe</h2>
  </div>
  <%= form_with url: games_path, method: :post do |form| %>
    <div class="mdl-card__supporting-text">
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <%= form.text_field :player1, class: 'mdl-textfield__input', id: 'textfield1' %>
        <%= form.label :player1, { class: 'mdl-textfield__label' } %>
      </div>
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        <%= form.text_field :player2, class: 'mdl-textfield__input', id: 'textfield1' %>
        <%= form.label :player2, { class: 'mdl-textfield__label' } %>
      </div>
    </div>
    <div class="mdl-card__actions mdl-card--border">
      <%= form.submit 'Start!', class: 'mdl-button mdl-js-button mdl-button--raised' %>
    </div>
  <% end %>
</div>

app/views/games/show.html.erb
<div class="mdl-card mdl-shadow--2dp">
  <div class="mdl-card__title">
    <% if @game.winner %>
      <h1 class="mdl-card__title-text winner-text">Winner: <%= @game.winner.name %></h1>
    <% elsif @game.draw?%>
      <h1 class="mdl-card__title-text draw-text">Draw in the game</h1>
    <% else %>
      <h2 class="mdl-card__title-text"><%= @game.player_name %>'s turn</h2>
    <% end %>
  </div>
  <div class="mdl-card__supporting-text">
    <div class="board">
      <% (1..9).each do |i| %>
        <div class="cell" data-cell>
          <% if @game.send("field#{i}_empty?") %>
            <%= form_with url: game_path(@game, field_index: i), method: :put do |form| %>
              <%= form.submit '', class: 'step-button' do %>c
              <% end %>
            <% end %>
          <% else %>
            <i class="material-icons icon <%= winning_class(@game.win_condition, i) %>"><%= icon_name(@game.send("field#{i}")) %></i>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="mdl-card__actions">
    <%= form_with url: game_restarts_path(@game) do |form| %>
      <%= form.submit 'Restart', class: 'mdl-button mdl-js-button mdl-button--raised' %>
    <% end %>
    <%= form_with url: new_game_path, method: :get do |form| %>
      <%= form.submit 'New game', class: 'mdl-button mdl-js-button mdl-button--raised' %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicTacToe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/icon?family=Material+Icons' %>
    <%= stylesheet_link_tag 'https://code.getmdl.io/1.3.0/material.indigo-pink.min.css' %>
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id="flash-messages">
      <%= render partial: 'shared/alert' %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/shared/_alert.html.erb
<% flash.each do |_type, message| %>
  <div
    data-controller="notification"
    data-notification-delay-value="4000"
    class="transition transform duration-1000 hidden"
    data-transition-enter-from="opacity-0 translate-x-6"
    data-transition-enter-to="opacity-100 translate-x-0"
    data-transition-leave-from="opacity-100 translate-x-0"
    data-transition-leave-to="opacity-0 translate-x-6"
  >
    <div id="flashAlert" class="flash-alert">
      <i class="material-icons">error_outline</i>
      <span><%= message %></span>
    </div>
  </div>
<% end %>